final: prev: let
  inherit (builtins) elemAt;

  github-tags = ["google-antigravity/antigravity-cli" "1.2.11"];
  version = elemAt github-tags 1;

  # Auto-generated by the overlay hash refresh workflow from release assets.
  source-url-aarch64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.11/agy_cli_mac_arm64.tar.gz";
  source-url-aarch64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.11/agy_cli_linux_arm64.tar.gz";
  source-url-x86_64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.11/agy_cli_mac_x64.tar.gz";
  source-url-x86_64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.11/agy_cli_linux_x64.tar.gz";

  # Keep these as top-level `hash-*` variables (not inlined in `sources`):
  # `.github/workflows/renovate_overlay_hashes.yaml` parses and rewrites them.
  hash-src-aarch64-darwin = "sha256-Q3qBPNfGBsy7MYCIaIf8aTYcKP6OiAMns7giAa+pAMw=";
  hash-src-aarch64-linux = "sha256-AVE7xh+VkjUwRbqAHrtAf7zLiYT8v95ZG8a2gbJOkrw=";
  hash-src-x86_64-darwin = "sha256-7gvVsJupP3Fie39wnQcLqAyKplZq7CZKFBneJMNcLzc=";
  hash-src-x86_64-linux = "sha256-yRxixeb6lU9afh17mtQX10nbSqYKS6Cz1gTewbZF0ZA=";
in {
  antigravity-cli = prev.antigravity-cli.overrideAttrs (old: let
    sources = prev.lib.mapAttrs (_: source: prev.fetchurl source) {
      x86_64-linux = {
        url = source-url-x86_64-linux;
        hash = hash-src-x86_64-linux;
      };
      aarch64-linux = {
        url = source-url-aarch64-linux;
        hash = hash-src-aarch64-linux;
      };
      aarch64-darwin = {
        url = source-url-aarch64-darwin;
        hash = hash-src-aarch64-darwin;
      };
      x86_64-darwin = {
        url = source-url-x86_64-darwin;
        hash = hash-src-x86_64-darwin;
      };
    };
  in {
    inherit version;
    src =
      sources.${prev.stdenv.hostPlatform.system}
      or (throw "Unsupported system: ${prev.stdenv.hostPlatform.system}");
    sourceRoot = ".";
    passthru = (old.passthru or {}) // {inherit sources;};
  });
}
