final: prev: let
  inherit (builtins) elemAt;

  github-tags = ["google-antigravity/antigravity-cli" "1.2.14"];
  version = elemAt github-tags 1;

  # Auto-generated by the overlay hash refresh workflow from release assets.
  source-url-aarch64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.14/agy_cli_mac_arm64.tar.gz";
  source-url-aarch64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.14/agy_cli_linux_arm64.tar.gz";
  source-url-x86_64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.14/agy_cli_mac_x64.tar.gz";
  source-url-x86_64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.2.14/agy_cli_linux_x64.tar.gz";

  # Keep these as top-level `hash-*` variables (not inlined in `sources`):
  # `.github/workflows/renovate_overlay_hashes.yaml` parses and rewrites them.
  hash-src-aarch64-darwin = "sha256-Ro7cxFS2uxwyHY1CWRoWrOTRodYopPHOla0jbJ7kzBk=";
  hash-src-aarch64-linux = "sha256-O0DDuqskW0OkEAfB22TfUfXxYrYFn8xKRQRzHyaJ0wE=";
  hash-src-x86_64-darwin = "sha256-OTZMwk57KwWkoBOMYNXV2jnfn7dt7cnj9LdKFoUS/NY=";
  hash-src-x86_64-linux = "sha256-aM9NIhy2LgKJJFQ509N/WZvcjgxOHj2uA/MmRjoMJtw=";
in {
  antigravity-cli = prev.antigravity-cli.overrideAttrs (old: let
    sources = prev.lib.mapAttrs (_: source: prev.fetchurl source) {
      x86_64-linux = {
        url = source-url-x86_64-linux;
        hash = hash-src-x86_64-linux;
      };
      aarch64-linux = {
        url = source-url-aarch64-linux;
        hash = hash-src-aarch64-linux;
      };
      aarch64-darwin = {
        url = source-url-aarch64-darwin;
        hash = hash-src-aarch64-darwin;
      };
      x86_64-darwin = {
        url = source-url-x86_64-darwin;
        hash = hash-src-x86_64-darwin;
      };
    };
  in {
    inherit version;
    src =
      sources.${prev.stdenv.hostPlatform.system}
      or (throw "Unsupported system: ${prev.stdenv.hostPlatform.system}");
    sourceRoot = ".";
    passthru = (old.passthru or {}) // {inherit sources;};
  });
}
